### ISSUE TITLE
AttributeError: 'UltraMagicString' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by JanoValaska** [svleeuwen/sortedm2m-filter-horizontal-widget#19]
First of all, thank your this cool Django admin widget.

I am trying to install it into Python 3.7 venv with Django 2.2.23 and I am getting following error:

```
Collecting django-sortedm2m-filter-horizontal-widget
  Using cached django-sortedm2m-filter-horizontal-widget-1.3.2.tar.gz (41 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-774yy8xg/django_sortedm2m_filter_horizontal_widget.egg-info
      writing /tmp/pip-pip-egg-info-774yy8xg/django_sortedm2m_filter_horizontal_widget.egg-info/PKG-INFO
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zitn_ebw/django-sortedm2m-filter-horizontal-widget_177a6f7b0d934ab284d93739a623e6ea/setup.py", line 95, in <module>
          install_requires = ['django-sortedm2m'],
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 301, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 665, in write_pkg_info
          metadata.write_pkg_info(cmd.egg_info)
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 1136, in write_pkg_info
          self.write_pkg_file(pkg_info)
        File "/srv/venvs/dev.2mev.com/lib/python3.7/site-packages/setuptools/dist.py", line 234, in write_pkg_file
          if not long_description.endswith("\n"):
      AttributeError: 'UltraMagicString' object has no attribute 'endswith'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

The problem is this *special* string : https://github.com/svleeuwen/sortedm2m-filter-horizontal-widget/blob/master/setup.py#L30

As per this comment https://stackoverflow.com/a/1439009 this *special* string should not be needed so I would suggest to get rid of it.
Classic unicode string can be used as you can see in *parent*  django-sortedm2m library - https://github.com/jazzband/django-sortedm2m/blob/master/setup.py#L39

**Comment by JanoValaska** [comment]
Here is a pull request - https://github.com/svleeuwen/sortedm2m-filter-horizontal-widget/pull/20/files

**Comment by goetzc** [comment]
This is already fixed in master, https://github.com/svleeuwen/sortedm2m-filter-horizontal-widget/commit/367ff0ac8497360167465c67484984af10a7ccbf.

**Comment by kegan** [comment]
@svleeuwen Could we release the `master` branch? 🙏  This this bug already been fixed about a year ago. Thank you 😎

**Comment by svleeuwen** [comment]
Yes, will create a release tomorrow.

**Comment by svleeuwen** [comment]
This is finally fixed and released. Sorry for the ridiculous amount of time that went by.

Will be a lot faster on future changes, in part thanks to using Poetry.
